### ISSUE TITLE
Create snap packages

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/nuvolaplayer#273]
- Blocked by tiliado/nuvolaruntime#424
- Blocked by tiliado/nuvolasdk#5

[Snaps](http://snapcraft.io/) are universal Linux packages.

> Package any app for every Linux desktop, server, cloud or device, and deliver updates directly.

Depends on:

- [x] Introduce Nuvola SDK #269
- [x] Web App scripts should provide desktop file #263

My bug reports:

- ~~[Unable to fork a new WebProcess: Failed to execute child process "/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess" (No such file or directory).](https://bugs.launchpad.net/snappy/+bug/1648988)~~ We use CEF now.
- ~~[Support DBus-activatable apps](https://bugs.launchpad.net/snappy/+bug/1648990)~~ Not needed in Nuvola anymore.

Upstream Issues:

- [ ] Crucial: [Snap launching other snaps](https://bugs.launchpad.net/snappy/+bug/1639746)
- [ ] [Upstream use of build-time defined DATADIR incompatible with snaps relocation](https://bugs.launchpad.net/snappy/+bug/1583250)
- [ ] [Snappy needs to influence environment variables in applications](https://bugs.launchpad.net/snappy/+bug/1583259)
- [ ] [Snaps using libappindicator and unity7 plug can't show app-indicators](https://bugs.launchpad.net/snappy/+bug/1639988)
- [ ] [${SNAP}_${APP}.desktop created instead of {SNAP}.desktop (breaks mpris with vlc)](https://bugs.launchpad.net/snappy/+bug/1604887)
- [ ] [Sharing tmp directory across multiple commands in a snap app](https://bugs.launchpad.net/snappy/+bug/1552458)

**Comment by fenryxo** [comment]
I've just reported 2 upstream bugs:

-  [Unable to fork a new WebProcess: Failed to execute child process "/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess" (No such file or directory).](https://bugs.launchpad.net/snappy/+bug/1648988)
- [Support DBus-activatable apps](https://bugs.launchpad.net/snappy/+bug/1648990)

**Comment by fenryxo** [comment]
Hello @flexiondotorg. I propose to fix my example [1] first (I've added you as a collaborator for that repo) and then post the solution to my bug [2] as it may be useful also for other developers.

[1]: https://github.com/fenryxo/snapcraft-issues/tree/master/webkit-app
[2]: https://bugs.launchpad.net/snappy/+bug/1648988

**Comment by flexiondotorg** [comment]
@fenryxo For the WebKit issue I advise that you build webkit as a source part in the snap. I had to do this with `zenity` recently, for different reasons. The `snapcraft.yaml` looks something like this:

```
parts:
  # Build a minimal zenity from source, prevents dragging in WebKit et al.
  zenity:
    plugin: autotools
    configflags:
      - --prefix=/usr
    source: https://git.gnome.org/browse/zenity/snapshot/ZENITY_3_18_1_1.tar.xz
    build-packages:
      - gnome-common
      - libgtk-3-dev
      - libnotify-dev
      - yelp-tools
    stage:
      - usr/bin/zenity
      - usr/share/zenity

  client-test:
    plugin: dump
    source: http://example.org/$SNAPCRAFT_PROJECT_VERSION_amd64.deb
    source-type: deb
    after:
      - desktop-gtk2
      - zenity
    stage-packages:
      - libasound2
      - libavcodec-ffmpeg-extra56
      - libavformat-ffmpeg56
      - libcurl3
      - libgconf-2-4
      - libgl1-mesa-glx
      - libglu1-mesa
      - libgtk-3-0
      - libnotify4
      - libnss3
      - libpulse0
      - libssl1.0.0
      - libxss1
      - libxtst6
```

Hopefully that gives you the clues to proceed :-)
